name: Deploy to VM

on:
  workflow_dispatch:

env:
  PORT: ${{ secrets.PORT }}
  MONGO_AUTH_DB: ${{ secrets.MONGO_AUTH_DB }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JSON_SECRET: ${{ secrets.JSON_SECRET }}

jobs:
  build:
    uses: dscnitrourkela/project-dates/.github/workflows/build.yml@main
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

  deploy:
    runs-on: [self-hosted, dsc-main]
    defaults:
      run:
        shell: bash
    needs: build
    steps:
      - name: Remove existing env
        run: rm .env || true
      - name: Create Env
        run: |
          touch .env
          echo PORT=$PORT >> .env
          echo DATABASE_URL=$DATABASE_URL >> .env
          echo MONGO_AUTH_DB=$MONGO_AUTH_DB >> .env
      - name: Pull Docker Image
        run: docker pull ghcr.io/${{ github.repository }}:latest
      - name: Stop existing container
        run: docker stop project-dates || true
      - name: Remove stopped container
        run: docker rm project-dates || true
      - name: Start container
        run: docker run --name=project-dates --env-file=.env -v $JSON_SECRET -p $PORT:$PORT -d ghcr.io/${{ github.repository }}:latest
